# FROM nginx:1.21.3-alpine
# RUN rm /etc/nginx/conf.d/default.conf
# COPY ./default.conf /etc/nginx/conf.d/default.conf
# RUN mkdir -p /app/staticfiles
# RUN mkdir -p /app/mediafiles

FROM nginx:1.21.3-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf